jobs:
  - name: pkg0
    plan:
      - task: install
        config:
         platform: linux
         image_resource:
           type: docker-image
           source: {repository: ubuntu}
         run:
           path: echo
           args: ["Hello, world2!"]

  - name: pkg1
    plan:
      - task: install
        config:
         platform: linux
         image_resource:
           type: docker-image
           source: {repository: ubuntu}
         run:
           path: echo
           args: ["Hello, world2!"]

  - name: pkg2
    plan:
      - task: install
        config:
         platform: linux
         image_resource:
           type: docker-image
           source: {repository: ubuntu}
         run:
           path: echo
           args: ["Hello, world2!"]

  - name: pkg3
    plan:
      - task: install
        config:
         platform: linux
         image_resource:
           type: docker-image
           source: {repository: ubuntu}
         run:
           path: echo
           args: ["Hello, world2!"]

  - name: pkg4
    plan:
      - task: install
        config:
         platform: linux
         image_resource:
           type: docker-image
           source: {repository: ubuntu}
         run:
           path: echo
           args: ["Hello, world2!"]

  - name: pkg5
    plan:
      - task: install
        config:
         platform: linux
         image_resource:
           type: docker-image
           source: {repository: ubuntu}
         run:
           path: echo
           args: ["Hello, world2!"]

  - name: pkg6
    plan:
      - task: install
        config:
         platform: linux
         image_resource:
           type: docker-image
           source: {repository: ubuntu}
         run:
           path: echo
           args: ["Hello, world2!"]

  - name: pkg7
    plan:
      - task: install
        config:
         platform: linux
         image_resource:
           type: docker-image
           source: {repository: ubuntu}
         run:
           path: echo
           args: ["Hello, world2!"]

  - name: pkg8
    plan:
      - task: install
        config:
         platform: linux
         image_resource:
           type: docker-image
           source: {repository: ubuntu}
         run:
           path: echo
           args: ["Hello, world2!"]

  - name: pkg9
    plan:
      - task: install
        config:
         platform: linux
         image_resource:
           type: docker-image
           source: {repository: ubuntu}
         run:
           path: echo
           args: ["Hello, world2!"]

  - name: pkg10
    plan:
      - task: install
        config:
         platform: linux
         image_resource:
           type: docker-image
           source: {repository: ubuntu}
         run:
           path: echo
           args: ["Hello, world2!"]

  - name: pkg10_centos
    plan:
      - task: install
        config:
         platform: linux
         image_resource:
           type: docker-image
           source: {repository: ubuntu}
         run:
           path: echo
           args: ["Hello, world2!"]

  - name: pkg11
    plan:
      - task: install
        config:
         platform: linux
         image_resource:
           type: docker-image
           source: {repository: ubuntu}
         run:
           path: echo
           args: ["Hello, world2!"]
  - name: pkg12
    plan:
      - task: install
        config:
         platform: linux
         image_resource:
           type: docker-image
           source: {repository: ubuntu}
         run:
           path: echo
           args: ["Hello, world2!"]

  - name: pkg13
    plan:
      - task: install
        config:
         platform: linux
         image_resource:
           type: docker-image
           source: {repository: ubuntu}
         run:
           path: echo
           args: ["Hello, world2!"]

  - name: pkg14
    plan:
      - task: install
        config:
         platform: linux
         image_resource:
           type: docker-image
           source: {repository: ubuntu}
         run:
           path: echo
           args: ["Hello, world2!"]

  - name: pkg15
    plan:
      - task: install
        config:
         platform: linux
         image_resource:
           type: docker-image
           source: {repository: ubuntu}
         run:
           path: echo
           args: ["Hello, world2!"]

